length=20;
height=6;
width=20;
proportion=2.5;
difference(){
cube(size=[length,width,height],center=true);
translate([0,-width/proportion,height/3])
     cube(size=[length/proportion,width*4,height],center=true);
translate([-length/proportion,0,height/3])
     cube(size=[length*4,width/proportion,height],center=true);
};